services:
  vote:
    build: ./vote/
    ports:
      - "5000:5000"
    networks:
      - front-tier
      - back-tier
  result:
    build: ./result/
    ports:
      - "4000:4000"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db
  seed-data:
    build: ./seed-data/
    networks:
      - front-tier
  worker:
    build: ./worker/
    networks:
      - back-tier
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "/healthchecks/postgres.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  # nginx:
  #   build: ./nginx/
  #   networks:
  #     - front-tier

networks:
  front-tier:
    name: front-tier
  back-tier:
    name: back-tier

volumes:
  postgresqldata:
  postgres-db-data:
