services:
  vote:
    build: ./vote/
    ports:
      - "5000:5000"
    networks:
      - front-tier
      - back-tier
  result:
    build: ./result/
    ports:
      - "4000:4000"
    networks:
      - front-tier
      - back-tier
  seed-data:
    build: ./seed-data/
    networks:
      - front-tier
  worker:
    build: ./worker/
  nginx:
    build: ./nginx/
    networks:
      - front-tier
  scriptpostgre:
    image: postgres
    restart: always
    volumes:
      - ./postgre.sh:/docker-entrypoint-initdb.d/postgre.sh
  scriptredis:
    image: redis
    volumes:
      - ./redis.sh:/docker-entrypoint-initdb.d/redis.sh

networks:
  front-tier:
    name: front-tier
  back-tier:
    name: back-tier
